'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

export default function Studio() {
  const [status, setStatus] = useState('Ready to build');
  return <main className="studio-shell"><header className="studio-nav"><Link href="/" className="studio-back">← Back to Agentic CAD</Link><span className="studio-title">Live workspace <i className="status-dot" /> {status}</span><Button variant="outline" onClick={() => setStatus('Export queued · Studio preview')}>Export STEP <span>↗</span></Button></header><section className="studio-grid"><aside className="studio-brief"><p className="eyebrow">DESIGN BRIEF</p><h1>Describe a part.<br /><em>Build the system.</em></h1><textarea defaultValue="Create a spur gear with 20 teeth, module 2, a 10mm bore, and 5mm thickness." /><Button onClick={() => setStatus('Solid rebuilt · evaluation complete')}>Generate design <span>→</span></Button><div className="studio-note"><i className="status-dot" /> Local geometry engine <strong>Replicad</strong></div></aside><section className="studio-viewport" aria-label="CAD workspace preview"><div className="studio-grid-lines" /><div className="studio-gear" /><div className="studio-meta">SPUR GEAR / LIVE SOLID <span>OPEN CASCADE · READY</span></div><div className="studio-bottom"><strong>20T · MODULE 2.0</strong><span>Valid solid · 10mm bore · 5mm thickness</span></div></section><aside className="studio-inspector"><div className="inspector-tabs"><span className="active">Parameters</span><span>Graph</span><span>Score</span></div>{['Teeth','Module','Bore diameter','Thickness'].map((label,index) => <label key={label}><span>{label}<output>{[20,'2.00 mm','10.00 mm','5.00 mm'][index]}</output></span><input type="range" min="1" max="100" defaultValue={[40,30,48,25][index]} /></label>)}<div className="studio-health"><p>BUILD STATUS <strong>HEALTHY</strong></p><span>Geometry <b>Valid solid</b></span><span>Pitch diameter <b>40.0 mm</b></span><span>Last build <b>just now</b></span></div></aside></section></main>;
}
