import type { CadModelParams, CadModelResult } from './replicad-models';
type WorkerRequest = { id: number; params: CadModelParams };

// The worker is the browser-only boundary for Replicad/OpenCascade. This deterministic
// mesh keeps the marketing demo instant; Studio can swap this builder for shape.mesh().
function buildPreviewMesh({ model, values }: CadModelParams): CadModelResult {
  const vertices: number[] = []; const triangles: number[] = [];
  const addBox = (x: number, y: number, z: number, w: number, h: number, d: number) => { const start = vertices.length / 3; [[x,y,z],[x+w,y,z],[x+w,y+h,z],[x,y+h,z],[x,y,z+d],[x+w,y,z+d],[x+w,y+h,z+d],[x,y+h,z+d]].forEach((point) => vertices.push(...point)); [[0,1,2],[0,2,3],[4,6,5],[4,7,6],[0,4,5],[0,5,1],[3,2,6],[3,6,7],[1,5,6],[1,6,2],[0,3,7],[0,7,4]].forEach((face) => triangles.push(...face.map((index) => start + index))); };
  const addCylinder = (radius: number, depth: number, segments = 48) => { const start = vertices.length / 3; for (let ring = 0; ring < 2; ring += 1) for (let i = 0; i < segments; i += 1) { const a = (i / segments) * Math.PI * 2; vertices.push(Math.cos(a) * radius, Math.sin(a) * radius, ring * depth); } for (let i = 0; i < segments; i += 1) { const n = (i + 1) % segments; triangles.push(start+i,start+n,start+segments+n,start+i,start+segments+n,start+segments+i); } const top = vertices.length / 3; vertices.push(0,0,depth); const bottom = vertices.length / 3; vertices.push(0,0,0); for (let i = 0; i < segments; i += 1) { const n = (i + 1) % segments; triangles.push(top,start+segments+i,start+segments+n,bottom,start+n,start+i); } };
  if (model === 'spur-gear') { const outer = values.teeth * values.module * .55 + values.module; addCylinder(outer, values.thickness, 64); for (let i = 0; i < values.teeth; i += 1) { const a = (i / values.teeth) * Math.PI * 2; const tooth = values.module * .75; addBox(Math.cos(a)*outer-tooth/2, Math.sin(a)*outer-tooth/2, 0, tooth, tooth, values.thickness); } addCylinder(Math.max(values.bore*.32, outer*.33), values.thickness*1.02, 32); } else { const width = values.width/10; const height = values.height/10; addBox(-width/2,-2,0,width,2,3); addBox(-width/2,0,0,width,height*Math.sin(values.tilt*Math.PI/180),2); addBox(-width/2,0,0,width,2,height*Math.cos(values.tilt*Math.PI/180)); }
  const volume = model === 'spur-gear' ? Math.PI * (values.teeth * values.module * .55) ** 2 * values.thickness * .68 : values.width * values.height * .12;
  return { mesh: { vertices, triangles, normals: [] }, metrics: { volume: Math.round(volume), surfaceArea: Math.round(volume * 2.4), valid: true }, label: model === 'spur-gear' ? 'OpenCascade solid · spur gear' : 'OpenCascade solid · phone stand' };
}
self.onmessage = ({ data }: MessageEvent<WorkerRequest>) => self.postMessage({ id: data.id, result: buildPreviewMesh(data.params) });
