'use client';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/magicui/button';
import { Badge } from '@/components/magicui/badge';
import { Slider } from '@/components/magicui/slider';
import { TooltipHint as Tooltip } from '@/components/magicui/tooltip';
import type { CadModelId, CadModelParams, CadModelResult, CadModelValues } from './replicad-models';
import { defaultCadValues, labelForModel } from './replicad-models';

function Scene({ result }: { result: CadModelResult | null }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const sceneRef = useRef<{ cleanup: () => void; group: { rotation: { x: number; y: number; z: number }; scale: { setScalar: (value: number) => void } } } | null>(null); const [drag, setDrag] = useState(false); const last = useRef({ x: 0, y: 0 });
  useEffect(() => { let disposed = false; import('three').then((THREE) => { if (disposed || !canvasRef.current) return; const canvas = canvasRef.current; const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(35, 1, .1, 1000); camera.position.set(0,-4,12); scene.add(new THREE.AmbientLight(0xffefe5,1.8)); const light = new THREE.DirectionalLight(0xffb18f,4); light.position.set(4,5,8); scene.add(light); const group = new THREE.Group(); scene.add(group); const resize = () => { const rect = canvas.getBoundingClientRect(); renderer.setSize(rect.width,rect.height,false); camera.aspect = rect.width/Math.max(rect.height,1); camera.updateProjectionMatrix(); }; resize(); window.addEventListener('resize',resize); if (result) { const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position',new THREE.Float32BufferAttribute(result.mesh.vertices,3)); geometry.setIndex(result.mesh.triangles); geometry.computeVertexNormals(); const mesh = new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({ color:0xe56e46, roughness:.34, metalness:.45 })); mesh.rotation.x = Math.PI/2; group.add(mesh); } let raf = 0; const animate = () => { raf=requestAnimationFrame(animate); if (!drag) group.rotation.z += .002; renderer.render(scene,camera); }; animate(); sceneRef.current = { group, cleanup: () => { cancelAnimationFrame(raf); window.removeEventListener('resize',resize); renderer.dispose(); } }; }); return () => { disposed=true; sceneRef.current?.cleanup(); sceneRef.current=null; }; }, [result, drag]);
  return <div className="cad-scene" onPointerDown={(event) => { setDrag(true); last.current={x:event.clientX,y:event.clientY}; }} onPointerMove={(event) => { if (!drag || !sceneRef.current) return; sceneRef.current.group.rotation.y += (event.clientX-last.current.x)*.01; sceneRef.current.group.rotation.x += (event.clientY-last.current.y)*.01; last.current={x:event.clientX,y:event.clientY}; }} onPointerUp={() => setDrag(false)} onPointerLeave={() => setDrag(false)} onWheel={(event) => sceneRef.current?.group.scale.setScalar(Math.max(.65,Math.min(1.45,1-event.deltaY*.0006)))}><canvas ref={canvasRef} /><div className="scene-grid" /><span className="scene-axis scene-axis-x">X</span><span className="scene-axis scene-axis-y">Y</span></div>;
}

export function CadDemo() {
  const [model,setModel] = useState<CadModelId>('spur-gear'); const [values,setValues] = useState<CadModelValues>(defaultCadValues); const [result,setResult] = useState<CadModelResult|null>(null); const worker = useRef<Worker|null>(null); const requestId = useRef(0);
  useEffect(() => { const nextWorker = new Worker(new URL('./cad-worker.ts',import.meta.url)); worker.current=nextWorker; nextWorker.onmessage=(event: MessageEvent<{id:number;result:CadModelResult}>)=>setResult(event.data.result); return () => nextWorker.terminate(); }, []);
  useEffect(() => { const params: CadModelParams={model,values}; worker.current?.postMessage({id:++requestId.current,params}); }, [model,values]);
  const setValue = (key: keyof CadModelValues,value:number) => setValues((current)=>({...current,[key]:value})); const gear=model==='spur-gear';
  return <div className="cad-demo" id="demo"><div className="demo-toolbar"><div><Badge>LIVE GEOMETRY</Badge><span className="demo-kicker">Replicad / OpenCascade</span></div><div className="demo-actions"><Tooltip label="Export is part of Studio"><Button variant="ghost" disabled>Export STEP</Button></Tooltip><Button variant="ghost" disabled>Export STL</Button></div></div><div className="demo-grid"><div className="demo-canvas"><Scene result={result}/><div className="canvas-label canvas-label-top">{labelForModel(model).toUpperCase()} / PREVIEW</div><div className="canvas-label canvas-label-bottom"><span><i className="status-dot"/> {result?.label??'Building mesh'}</span><span>Drag to orbit · Scroll to zoom</span></div></div><aside className="demo-controls"><div className="control-header"><span>MODEL</span><strong>{gear?'01':'02'}</strong></div><div className="model-switcher"><button className={gear?'active':''} onClick={()=>setModel('spur-gear')}>Spur gear <span>↗</span></button><button className={!gear?'active':''} onClick={()=>setModel('phone-stand')}>Phone stand <span>↗</span></button></div><div className="control-header control-header-spaced"><span>PARAMETERS</span><strong>LIVE</strong></div>{gear?<><Control label="Teeth" value={values.teeth} min={8} max={40} step={1} onChange={(value)=>setValue('teeth',value)}/><Control label="Module" value={values.module} min={1} max={4} step={.1} suffix="mm" onChange={(value)=>setValue('module',value)}/><Control label="Bore" value={values.bore} min={4} max={18} step={.5} suffix="mm" onChange={(value)=>setValue('bore',value)}/><Control label="Thickness" value={values.thickness} min={2} max={12} step={.5} suffix="mm" onChange={(value)=>setValue('thickness',value)}/></>:<><Control label="Tilt" value={values.tilt} min={45} max={82} step={1} suffix="°" onChange={(value)=>setValue('tilt',value)}/><Control label="Width" value={values.width} min={48} max={100} step={1} suffix="mm" onChange={(value)=>setValue('width',value)}/><Control label="Height" value={values.height} min={60} max={130} step={1} suffix="mm" onChange={(value)=>setValue('height',value)}/></>}<div className="metric-row"><span>Geometry status</span><strong><i className="status-dot"/> Valid solid</strong></div><div className="metric-row"><span>Volume</span><strong>{result?.metrics.volume??'—'} mm³</strong></div><div className="metric-row"><span>Surface area</span><strong>{result?.metrics.surfaceArea??'—'} mm²</strong></div><Button className="reset-button" variant="outline" onClick={()=>setValues(defaultCadValues)}>Reset parameters <span>↺</span></Button></aside></div></div>;
}
function Control({label,value,min,max,step,suffix='',onChange}:{label:string;value:number;min:number;max:number;step:number;suffix?:string;onChange:(value:number)=>void}) { return <label className="cad-control"><span>{label}<output>{value.toFixed(step<1?1:0)}{suffix}</output></span><Slider min={min} max={max} step={step} value={[value]} onValueChange={(nextValue)=>onChange(nextValue[0] ?? value)}/></label>; }
