'use client';

import { useEffect, useRef, useState } from 'react';
import { Download, Maximize2, Minus, PencilRuler, Plus } from 'lucide-react';

type Artifact = { id: string; filename: string; kind: string };

const ZOOM_MIN = 0.25;
const ZOOM_MAX = 4;

/** Renders a generated SVG drawing artifact (blueprint or sketch) with zoom and download. */
export function DrawingViewer({ artifacts, kind, emptyHint }: { artifacts: Artifact[]; kind: string; emptyHint: string }) {
  const artifact = artifacts.find((item) => item.kind === kind) ?? null;
  const family = kind.split('_')[0];
  const companions = artifacts.filter((item) => item.kind !== kind && item.kind.startsWith(family));
  const [svg, setSvg] = useState<string | null>(null);
  const [state, setState] = useState<'idle' | 'loading' | 'error'>('idle');
  const [zoom, setZoom] = useState(1);
  const requestId = useRef(0);

  useEffect(() => {
    if (!artifact) { setSvg(null); setState('idle'); return; }
    const request = ++requestId.current;
    setState('loading');
    setSvg(null);
    fetch(`/api/artifacts/${artifact.id}`)
      .then((response) => (response.ok ? response.text() : Promise.reject(new Error('unavailable'))))
      .then((text) => {
        // Ignore a response for a drawing the user has already navigated away from.
        if (request !== requestId.current) return;
        setSvg(text);
        setState('idle');
      })
      .catch(() => { if (request === requestId.current) setState('error'); });
  }, [artifact?.id]);

  if (!artifact) {
    return (
      <div className="wk-empty">
        <PencilRuler size={22} aria-hidden="true" />
        <strong>No drawing yet</strong>
        <span>{emptyHint}</span>
      </div>
    );
  }

  return (
    <div className="wk-draw">
      <div className="wk-draw-top">
        <span className="wk-label">{artifact.filename}</span>
        <div className="wk-ver-acts" style={{ marginLeft: 'auto' }}>
          <button type="button" className="wk-btn wk-btn-quiet wk-btn-icon" onClick={() => setZoom((z) => Math.max(ZOOM_MIN, z - 0.25))} disabled={zoom <= ZOOM_MIN} aria-label="Zoom out"><Minus size={14} /></button>
          <span className="wk-chip" aria-live="polite">{Math.round(zoom * 100)}%</span>
          <button type="button" className="wk-btn wk-btn-quiet wk-btn-icon" onClick={() => setZoom((z) => Math.min(ZOOM_MAX, z + 0.25))} disabled={zoom >= ZOOM_MAX} aria-label="Zoom in"><Plus size={14} /></button>
          <button type="button" className="wk-btn wk-btn-quiet wk-btn-icon" onClick={() => setZoom(1)} aria-label="Reset zoom"><Maximize2 size={14} /></button>
          <a className="wk-btn wk-btn-quiet wk-btn-icon" href={`/api/artifacts/${artifact.id}`} download={artifact.filename} aria-label={`Download ${artifact.filename}`}><Download size={14} /></a>
        </div>
      </div>
      <div className="wk-draw-stage">
        {state === 'loading' && <span className="wk-muted">Loading drawing…</span>}
        {state === 'error' && <span className="wk-muted">This drawing could not be loaded.</span>}
        {svg && (
          <div
            className="wk-draw-sheet"
            style={{ width: `${zoom * 100}%`, maxWidth: zoom <= 1 ? '100%' : 'none' }}
            /* Generated by our own worker and served from a same-origin owner-checked route. */
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        )}
      </div>
      {companions.length > 0 && (
        <div className="wk-draw-top" style={{ boxShadow: 'none' }}>
          <span className="wk-label">Also exported</span>
          {companions.map((item) => (
            <a key={item.id} className="wk-chip" href={`/api/artifacts/${item.id}`} download={item.filename}>{item.filename}</a>
          ))}
        </div>
      )}
    </div>
  );
}
