import { notFound } from 'next/navigation';
import Link from 'next/link';
import { SiteShell } from '@/components/app-shell/site-shell';
import { prisma } from '@/lib/prisma';
import { PublicCadPreview } from '@/components/cad/public-cad-preview';

export default async function PublicProject({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const project = await prisma.project.findFirst({ where: { slug, visibility: 'PUBLIC' }, include: { owner: { include: { profile: true } }, publishedRevision: { include: { artifacts: true } } } });
  if (!project?.publishedRevision) notFound();
  const metrics = project.publishedRevision.metrics && typeof project.publishedRevision.metrics === 'object' ? project.publishedRevision.metrics as { volume?: number; surfaceArea?: number; triangleCount?: number } : {};
  const validation = project.publishedRevision.validation && typeof project.publishedRevision.validation === 'object' ? project.publishedRevision.validation as { complete?: boolean; warnings?: string[] } : {};
  const previewArtifact = project.publishedRevision.artifacts.find((artifact) => artifact.kind === 'PREVIEW_MESH');
  return <SiteShell><main className="projects-page public-project-page"><header><div><p className="site-eyebrow">PUBLISHED DESIGN</p><h1>{project.title}</h1><span>{project.summary}</span><p>By <Link href={`/u/${project.owner.username}`}>{project.owner.profile?.displayName ?? project.owner.username}</Link></p></div><span className="public-project-revision">R{project.publishedRevision.revisionNumber} · Published</span></header><section className="public-project-preview"><PublicCadPreview slug={project.slug} artifactId={previewArtifact?.id ?? null} /></section><section className="public-project-grid"><div className="public-project-summary"><span className="codex-label">PUBLISHED REVISION</span><h2>Revision {project.publishedRevision.revisionNumber}</h2><p>{project.publishedRevision.isValid ? validation.warnings?.length ? 'Validated geometry with export warnings; review the findings before manufacturing.' : 'Validated OpenCascade BREP with inspectable export files.' : 'Pending validation.'}</p>{validation.warnings?.length ? <div className="public-project-warning" role="status"><strong>Build findings</strong><span>{validation.warnings.join(' ')}</span></div> : null}<dl><div><dt>Volume</dt><dd>{metrics.volume != null ? `${metrics.volume.toLocaleString()} mm³` : '—'}</dd></div><div><dt>Surface area</dt><dd>{metrics.surfaceArea != null ? `${metrics.surfaceArea.toLocaleString()} mm²` : '—'}</dd></div><div><dt>Triangles</dt><dd>{metrics.triangleCount?.toLocaleString() ?? '—'}</dd></div></dl></div><div className="public-project-artifacts"><span className="codex-label">PUBLISHED FILES</span>{project.publishedRevision.artifacts.length ? project.publishedRevision.artifacts.map((artifact) => <a key={artifact.id} href={`/api/public/projects/${project.slug}/artifacts/${artifact.id}`} className="public-project-artifact"><span>{artifact.filename}</span><small>{artifact.kind}</small></a>) : <p>No export files are available for this revision.</p>}</div></section></main></SiteShell>;
}
